spring:
    application:
        name: library-service
    datasource:
        url: jdbc:postgresql://develvm:5432/librarydb
        username: libraryuser
        password: librarypassword
        initialize: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
    cache:
        type: jcache
        cache-names: users, books
flyway:
    enabled: true
    schemas: library
borrow:
    maximum: 3
