language: java
jdk:
  - openjdk15

sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - ./gradlew clean test

after_success:
  - ./gradlew jacocoTestReport coveralls
