language: java
jdk:
  - openjdk15

sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw -B -V clean verify

after_success:
  - ./mvnw jacoco:report coveralls:report
