version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/library-domain"
    update_schedule: "daily"
    target_branch: "master"

  - package_manager: "java:gradle"
    directory: "/library-infrastructure"
    update_schedule: "daily"
    target_branch: "master"
