spring:
  application:
    name: library-service
  data:
    rest:
      basePath: /api
    elasticsearch:
      cluster-nodes: es01:9300
  datasource:
    url: jdbc:postgresql://db:5432/librarydb
    username: libraryuser
    password: librarypassword
    initialize: true
  jpa:
    properties:
      hibernate:
        default_schema: library
  flyway:
    schemas: library
  cache:
    cache-names: books,users
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1200s
  jackson:
    default-property-inclusion: non_null

borrow:
  maximumBorrows: 3
  borrowLength: 2

logging:
  level:
    org.springframework.web: WARN
    org.hibernate: WARN
  file: /var/log/libraryservice.log
